---
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: dokimi-mirrorset
spec:
  imageDigestMirrors:
  - mirrors:
    - brew.registry.redhat.io
    source: registry.redhat.io
